[build]
publish = "public"
command = "hugo --gc"
# need to debug line -- currently making builds fail
#ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF archetypes/* assets/* content/* data/* layouts/* static/* themes/*"

[context.production.environment]
  HUGO_VERSION = "0.139.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
 
[context.deploy-preview.environment]
  HUGO_VERSION = "0.139.0"
  
[context.deploy-preview]
  command = "hugo --gc -b $STORIES__DEPLOY_PRIME_URL"

[build.processing]
  skip_processing = true
  
